### PR TITLE
Feature debug helper

### PR DESCRIPTION
**Pull request by jackd248**
Some debug helper for development purpose. 

Needs some work for drupal features.

### CODE REVIEW

**Review by Defcon0 — COMMENTED** [review]
Added code for getting the db password and db name out of the .env file. This implies fixing the deployment for drupal projects so that the settings.local.php contains the references to the .env file. I think this is a good practice anyway. @jackd248  What do u think?

**Comment by Defcon0** [comment]
Just did the support for drupal logs using monolog module. I noted that in

https://github.com/xima-media/xima-deployer-tools/pull/10/commits/285b96a7125029d283211ae1acc85cb169ad7f61#diff-d64f6e21bf074a6b3089e027e2a1df46b42dc47387406abc5ea1f251e68f72c2

I needed to limit my log data to certain things (#, Date, Level, Message) but in the current log file data we have additional bits of data ("context" and "extra"):

```
[2024-04-02T11:47:50.326481+00:00] system.NOTICE: Module config_filter has an entry in the system.schema key/value storage, but is missing from your site. <a href="https://www.drupal.org/node/3137656">More information about this error</a>. [] {"referer":"","ip":"127.0.0.1","request_uri":"http://default/","uid":0,"user":""}
```

Also see a typical regex for monolog entries: https://regex101.com/library/Xu8huk?amp;search=card&orderBy=MOST_RECENT&page=101&search=&filterFlavors=pcre&filterFlavors=javascript

So I think we might need a more dynamic way of handling the "inspect" function (adjust the viewed data) done here
https://github.com/xima-media/xima-deployer-tools/pull/10/files#diff-a23a2b319349fdf1192e582fbf674689cc68953dcfd3a12537a570dc7b843483R63

**Comment by Defcon0** [comment]
Also a limitation for 145 characters for the log messages instead of 150 would be cool so that the table wouldn't break in a default config terminal setup in linux systems :)

**Comment by jackd248** [comment]
> Added code for getting the db password and db name out of the .env file. This implies fixing the deployment for drupal projects so that the settings.local.php contains the references to the .env file. I think this is a good practice anyway. @jackd248 What do u think?

I remember this discussion with pmi. I agree with you, a standardised use of the .env files seems reasonable.

**Comment by jackd248** [comment]
> Just did the support for drupal logs using monolog module. I noted that in
> 
> [285b96a#diff-d64f6e21bf074a6b3089e027e2a1df46b42dc47387406abc5ea1f251e68f72c2](https://github.com/xima-media/xima-deployer-tools/commit/285b96a7125029d283211ae1acc85cb169ad7f61#diff-d64f6e21bf074a6b3089e027e2a1df46b42dc47387406abc5ea1f251e68f72c2)
> 
> I needed to limit my log data to certain things (#, Date, Level, Message) but in the current log file data we have additional bits of data ("context" and "extra"):
> 
> ```
> [2024-04-02T11:47:50.326481+00:00] system.NOTICE: Module config_filter has an entry in the system.schema key/value storage, but is missing from your site. <a href="https://www.drupal.org/node/3137656">More information about this error</a>. [] {"referer":"","ip":"127.0.0.1","request_uri":"http://default/","uid":0,"user":""}
> ```
> 
> Also see a typical regex for monolog entries: https://regex101.com/library/Xu8huk?amp;search=card&orderBy=MOST_RECENT&page=101&search=&filterFlavors=pcre&filterFlavors=javascript
> 
> So I think we might need a more dynamic way of handling the "inspect" function (adjust the viewed data) done here https://github.com/xima-media/xima-deployer-tools/pull/10/files#diff-a23a2b319349fdf1192e582fbf674689cc68953dcfd3a12537a570dc7b843483R63

You can actually define the headers an lines as you need them. There shouldn't be a limitation to only date, level and message (but this should be the first 3 values of a log entry). Or do you mean to distinguish between "list view" and "detail view" of log entries?

**Comment by jackd248** [comment]
> Also a limitation for 145 characters for the log messages instead of 150 would be cool so that the table wouldn't break in a default config terminal setup in linux systems :)

Seems reasonable, feel free to contribute ;)

**Comment by Defcon0** [comment]
> You can actually define the headers an lines as you need them. There shouldn't be a limitation to only date, level and message (but this should be the first 3 values of a log entry). Or do you mean to distinguish between "list view" and "detail view" of log entries?

Yep, it would be good to distinguish between list and detail. Since in drupal the "extra" field might contain very much data (JSON e.g.), it would've been no option to put it into the list view.

**Comment by Defcon0** [comment]
> Seems reasonable, feel free to contribute ;)
Done :)

**Comment by DennisPX0** [comment]
Thanks for the adjustments for distinguishing between list and detail logging. Works good!

I added the changes for drupal logging.

2 thinks came to my mind:

1. I don't quite get the point of asking whether to inspect or not: https://github.com/xima-media/xima-deployer-tools/blob/feature-debug-helper/deployer/debug/task/debug_log_app.php#L59 . Is this really needed?
1. Currently, only the last 10 log lines can be inspected. Should be ok in most cases, but still seems a bit fixed to me. Maybe we ask for the limit instead of the first point? The limit also seems a bit depending on the context.

What do u think?

**Comment by jackd248** [comment]
> I don't quite get the point of asking whether to inspect or not: https://github.com/xima-media/xima-deployer-tools/blob/feature-debug-helper/deployer/debug/task/debug_log_app.php#L59 . Is this really needed?

I don't think it's really needed. The task should only give a preview of the last log entries. The query for inspection is just a kind of a breakpoint, so that the selection of the log entry for the inspection does not appear immediately below and the preview table further up disappears. In many cases, a look at the preview table is probably sufficient. 

> Currently, only the last 10 log lines can be inspected. Should be ok in most cases, but still seems a bit fixed to me. Maybe we ask for the limit instead of the first point? The limit also seems a bit depending on the context.

You can extend the functionality as you need them (e.g. with an configurable param for tails `-n '), but I don't recommend to build a complex log browser.

**Comment by DennisPX0** [comment]
1. Makes sense
2. Just added a config option `debug_log_tail_options`

**Pull request merged**
